### ISSUE TITLE
[1.19.2] Crash on startup

### ISSUE THREAD

**Issue by DeleteMetaInf** [MehVahdJukaar/modelfix-multi#3]
The game crashes on startup with Model Gap Fix installed. Disabling it lets the game boot as expected.

**Crash report:** https://pastebin.com/raw/7CPPKvgY

### Versions
* **Minecraft:** 1.19.2 (latest)
* **Forge:** 43.1.27 (latest)
* **Model Gap Fix:** 1.4 (latest)

**Comment by MehVahdJukaar** [comment]
If you are missing a dependency the game is bound to crash

**Comment by DeleteMetaInf** [comment]
Unlike Tyrius1, I wasn’t missing any dependencies, so I’m not sure why my game crashed. My game launched just fine without Model Gap Fix installed.

**Comment by MehVahdJukaar** [comment]
I believe I fixed the original bug you reports a month ago, tho I never verified it. If it doesn't crash now then it is indeed fixed

**Comment by Lesley-Black-Velvet** [comment]
Apparently, I tried loading it with GeckoLib installed and it still crashed. Plus we both have the same issue.

**Comment by MehVahdJukaar** [comment]
I need a crash report

**Comment by Lesley-Black-Velvet** [comment]
Ah, update, nevermind.

I just downloaded NBT Deadlock begone and it now works fine.

**Comment by MehVahdJukaar** [comment]
Cool I'll close this then
